language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
    - os: windows
test:
  - npm i -g neon-cli
  - neon build
  - neon build --release
